services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: postgres_bookings_db
    environment:
      - 'POSTGRES_DB=bookings'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
